CREATE TABLE accounts (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	owner_name VARCHAR(100) NOT NULL,
	currency VARCHAR(3) NOT NULL DEFAULT 'TRY',
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'PASSIVE', 'FROZEN', 'CLOSED')),
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()	
);